FROM python:3.9

WORKDIR /app

COPY backend/requirements.txt ./

RUN pip install  -r requirements.txt

# Copy the source code

COPY backend/app.py ./
COPY ./src ./src

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8500", "--reload"]
